#!/bin/sh

export PATH="/workspaces/toolchain/toolchain/clang/bin:/workspaces/toolchain/toolchain/gcc/bin:${PATH}"

export ARCH=arm
export CC=clang
export HOSTCC=clang
export CROSS_COMPILE=arm-linux-androideabi-
export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
export CFLAGS_WARN=-Wunused-but-set-variable

# Setup make Command
export xxx="KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y CFLAGS_WARN=-Wunused-but-set-variable ARCH=arm CROSS_COMPILE=arm-linux-androideabi- CC=clang HOSTCC=clang"

make O=out $xxx-j"$(nproc --all)"