name: Build Kernel

on:
  workflow_dispatch:

jobs:
  start-compiling:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download the file
      run: |
        cd ${GITHUB_WORKSPACE}
        export KBUILD_BUILD_USER="${{ github.actor }}"
        export KBUILD_BUILD_HOST="${{ github.event.inputs.DEVICE_NAME }}"
        chmod +x ba.sh
        export PATH="${PWD}/toolchain/clang/bin:${PWD}/toolchain/gcc/bin:${PATH}"
        ./ba.sh

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"

    - name: Add and Commit file
      run: |
        git add /home/runner/work/toolchain/toolchain/out/mm /home/runner/work/toolchain/toolchain/out/net /home/runner/work/toolchain/toolchain/out/security /home/runner/work/toolchain/toolchain/out/usr /home/runner/work/toolchain/toolchain/out/virt
        git commit -m "test build 3"
        git push
