name: Build Kernel

on:
  workflow_dispatch:

jobs:
  start-compiling:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download the file
      run: |
        cd ${GITHUB_WORKSPACE}
        export KBUILD_BUILD_USER="${{ github.actor }}"
        export KBUILD_BUILD_HOST="${{ github.event.inputs.DEVICE_NAME }}"
        chmod +x ba.sh
        export PATH="${PWD}/toolchain/clang/bin:${PWD}/toolchain/gcc/bin:${PATH}"
        ./ba.sh

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        export XX="${GITHUB_WORKSPACE}/out"

    - name: Add and Commit file
      run: |
        git add $XX/mm $XX/scripts $XX/security $XX/usr $XX/virt
        git commit -m "add 3rd"
        git push
