name: Sedot clang

on:
  workflow_dispatch:
  push:
    branches:
      - clang

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download the file
      run: |
        git lfs install
        git lfs push --all origin
        git lfs track "*.tar.gz"
        git add .gitattributes
        wget "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-release/clang-r450784d.tar.gz"
        tar xzvf clang-r450784d.tar.gz
        rm clang-r450784d.tar.gz
        rm android12L-release.tar.gz

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"

    - name: Add and Commit file
      run: |
        git add *
        git commit -m "Add clang toolchain v13-release"
        git push
