name: Sedot kernel

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download the file
      run: |
        git lfs install
        git lfs push --all origin
        git lfs track "*.zip"
        git add .gitattributes
        wget "https://github.com/rdbckp/a022f_kernel/archive/refs/heads/master.zip"
        unzip master.zip
        mv a022f_kernel-master/* .
        rm master.zip
        rm -rf a022f_kernel-master
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
    - name: Add and Commit file
      run: |
        git add *
        git commit -m "initial tree"
        git push
