name: Prebuilt Kernel

on: workflow_dispatch

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start Building Rookie Kernel
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          cd ${GITHUB_WORKSPACE}
          rm -rf out
          export KBUILD_BUILD_USER="${{ github.actor }}"
          export KBUILD_BUILD_HOST="${{ github.event.inputs.DEVICE_NAME }}"
          chmod +x build_kernel.sh
          ./build_kernel.sh
          cd out
          zip -r out.zip . -x "*/source/*"
          mv out.zip ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE} && rm -rf out

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
        
      - name: Add and Commit file
        run: |
          git add -A
          git commit -m "Ready to download"
          git push
        
